version: 2
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout

      - run:
          name: Deploying
          command: eb deploy CodeTemplaterTest-env

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master